name: new_version_update
version: 0.0.1
description: A Flutter package to check for new versions of your app on the Apple App Store and Google Play Store and show update dialog.
repository: https://github.com/AKB0N/new_version_update

dependencies:
  flutter:
    sdk: flutter
  html: ^0.15.5
  http: ^1.2.2
  package_info_plus: ^8.1.2
  url_launcher: ^6.3.1

environment:
  sdk: '>=3.5.4 <4.0.0'
  flutter: '>=3.27.0'

